# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Arbit Musings
email: mail@rohitja.in
description: > # this means to ignore newlines until "baseurl:"
  An eclectic collection of random ideas
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://rohitja.in" # the base hostname & protocol for your site
twitter_username: rohit7jain
github_username:  esawtooth
exclude: ['*.ipynb', '*.py']
# Build settings
markdown: kramdown
BLOG_DIR: ""
